In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
arr1 = np.array([1, 2, 3])
print(arr1)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)


[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Dimensions:", arr2.ndim)
print("Data type:", arr2.dtype)


Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [6]:
arr = np.arange(10, 51)
print(arr[arr % 2 == 0])
matrix = np.zeros((5, 5), dtype=int)
matrix[2, 2] = 1
print(matrix)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [12]:
arr = np.array([[[1,2],[2,3]]])
print(arr.shape,arr.size,arr.ndim,)
print(arr)

(1, 2, 2) 4 3
[[[1 2]
  [2 3]]]


In [13]:
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
arr = np.array([[1, 2], [3, 4]])
print(arr[1, 0])  # 3
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[1, 0, 1])  # 6
arr = np.array([0, 10, 20, 30, 40])
print(arr[1:4])  # [10 20 30]
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[:, 1:])  # [[2 3], [5 6]]


10
3
6
[10 20 30]
[[2 3]
 [5 6]]


In [14]:
arr = np.array([5, 10, 15, 20])
print(arr[arr > 10])  # [15 20]
arr = np.array([100, 200, 300, 400])
print(arr[[0, 2]])  # [100 300]
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)
print(reshaped.flatten())  # [1 2 3 4 5 6]


[15 20]
[100 300]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [15]:
arr = np.array([1, 2, 3])
view = arr.view()
copy = arr.copy()

arr[0] = 100
print(view)  # Reflects changes → [100 2 3]
print(copy)  # Doesn't reflect → [1 2 3]


[100   2   3]
[1 2 3]


In [16]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr[1, 1])  # Output: 5


5


In [17]:
print(arr[2, :])  # [7 8 9]
print(arr[arr > 5])  # [6 7 8 9]


[7 8 9]
[6 7 8 9]


In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]
print(a / b)  # [0.25 0.4  0.5]
print(a ** 2) # [1 4 9]


[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", arr.sum())             # 21
print("Mean:", arr.mean())           # 3.5
print("Max:", arr.max())             # 6
print("Min:", arr.min())             # 1
print("Standard Deviation:", arr.std())  # 1.707...
print("Sum across columns:", arr.sum(axis=0))  # [5 7 9]
print("Sum across rows:", arr.sum(axis=1))     # [6 15]


Sum: 21
Mean: 3.5
Max: 6
Min: 1
Standard Deviation: 1.707825127659933
Sum across columns: [5 7 9]
Sum across rows: [ 6 15]


In [20]:
arr = np.array([0, np.pi/2, np.pi])

print(np.sin(arr))  # [0. 1. 0.]
print(np.log([1, np.e, np.e**2]))  # [0. 1. 2.]
print(np.sqrt([1, 4, 9]))  # [1. 2. 3.]


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[0. 1. 2.]
[1. 2. 3.]


In [21]:
np.random.seed(42)  # For reproducibility

print(np.random.rand(2, 3))     # Uniform [0, 1)
print(np.random.randn(2, 3))    # Standard normal distribution
print(np.random.randint(1, 10, size=(2, 3)))  # Random ints
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

print(np.random.choice(arr, size=4))  # Random sample
arr = np.array([1, 2, 2, 3, 4])
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Variance:", np.var(arr))
arr = np.random.randint(1, 51, (3, 3))
print("Matrix:\n", arr)
print("Mean:", arr.mean())
arr = np.random.randn(1000)
print("Std Dev:", arr.std())


[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]
[[6 9 1]
 [3 7 4]]
[5 3 1 6 0 7 9 4 2 8]
[2 3 8 2]
Mean: 2.4
Median: 2.0
Variance: 1.04
Matrix:
 [[26  2 20]
 [28 47  7]
 [44  8 47]]
Mean: 25.444444444444443
Std Dev: 1.0561840563327511


In [22]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

dot = np.dot(a, b)
print(dot)
print(a @ b)          # New Python 3.5+ syntax
print(np.matmul(a, b))  # NumPy function
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.T)  # Transposed version (3x2)
from numpy.linalg import inv, det

matrix = np.array([[1, 2], [3, 4]])
inverse = inv(matrix)
print("Inverse:\n", inverse)

print("Determinant:", det(matrix))  # Output: -2.0
from numpy.linalg import eig

a = np.array([[2, 0], [0, 3]])
values, vectors = eig(a)

print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.hstack((a, b)))  # [1 2 3 4 5 6]
print(np.vstack((a, b)))
print(np.column_stack((a, b)))  # Shape: (3, 2)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.hsplit(arr, 2))  # Splits into 2 (2x2)
print(np.vsplit(arr, 2))  # Splits into 2 (1x4) arrays
arr = np.arange(12).reshape(6, 2)
print(np.vsplit(arr, 3))


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 4]
 [2 5]
 [3 6]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
[array([[0, 1],
       [2, 3]]), array([[4, 5],
       [6, 7]]), array([[ 8,  9],
       [10, 11]])]


In [23]:
arr = np.array([1, 2, 3])
print(arr + 10)  # [11 12 13]
a = np.array([[1], [2], [3]])  # Shape: (3,1)
b = np.array([10, 20, 30])     # Shape: (3,)
print(a + b)
arr = np.arange(1000000)
squared = []
for i in arr:
    squared.append(i ** 2)
arr = np.arange(1000000)
squared = arr ** 2
arr_list = list(range(1000))
arr_numpy = np.arange(1000)

print(arr_list.__sizeof__())      # Python list size
print(arr_numpy.nbytes)           # NumPy array memory size


[11 12 13]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
8040
8000


In [25]:
import numpy as np

marks = np.random.randint(0, 101, (5, 4))
print("Marks:\n", marks)

print("Avg per student:", marks.mean(axis=1))
print("Max per subject:", marks.max(axis=0))
print("Min per subject:", marks.min(axis=0))
print("Top total:", marks.sum(axis=1).max())


Marks:
 [[73 34 60 92]
 [53 62 78 96]
 [ 6 75 48 93]
 [84 30 57 60]
 [23 19 36  3]]
Avg per student: [64.75 72.25 55.5  57.75 20.25]
Max per subject: [84 75 78 96]
Min per subject: [ 6 19 36  3]
Top total: 289
