In [1]:



pip install numpy





SyntaxError: invalid syntax (1506401031.py, line 1)

In [2]:
pip install numpy



SyntaxError: invalid syntax (4265594094.py, line 1)

In [5]:

import numpy as np
a=np.array([1,2,3,7,7,7])
a

array([1, 2, 3])

In [6]:
b = np.array([[1,2,3,4],[1,1,1,1]])
b


array([[1, 2, 3, 4],
       [1, 1, 1, 1]])

In [7]:
b.ndim

2

In [8]:
b.shape

(2, 4)

In [9]:
b.dtype

dtype('int64')

In [10]:
b.itemsize

8

In [11]:
b.nbytes

64

In [12]:
a.nbytes

24

In [17]:
d = np.array([[1,2,3,4,6,5,4,3],[1,1,1,5,4,3,2,1]])
d

array([[1, 2, 3, 4, 6, 5, 4, 3],
       [1, 1, 1, 5, 4, 3, 2, 1]])

In [19]:
d[1,1]

np.int64(1)

In [20]:
d[0:]

array([[1, 2, 3, 4, 6, 5, 4, 3],
       [1, 1, 1, 5, 4, 3, 2, 1]])

In [22]:
d[:5]

array([[1, 2, 3, 4, 6, 5, 4, 3],
       [1, 1, 1, 5, 4, 3, 2, 1]])

In [32]:
f = np.array([[[1,2],[1,2],[2,5],[7,9]]])
f

array([[[1, 2],
        [1, 2],
        [2, 5],
        [7, 9]]])

In [33]:
f.ndim

3

In [34]:
f.ndim

3

In [35]:
f.ndim

3

In [37]:
g=np.zeros((5,3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
g=np.ones((5,3,6))
g

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [39]:
i = np.full((2,4),88)
i

array([[88, 88, 88, 88],
       [88, 88, 88, 88]])

In [44]:
p = np.random.rand(4,9)
p

array([[0.61564512, 0.92812999, 0.04636342, 0.90380823, 0.71307778,
        0.00118727, 0.96104271, 0.92518201, 0.9147515 ],
       [0.16926545, 0.14248626, 0.50311153, 0.46680827, 0.83210967,
        0.16076397, 0.82685077, 0.19979162, 0.16897236],
       [0.50716636, 0.81228682, 0.46815124, 0.06116116, 0.63194759,
        0.9040976 , 0.03691402, 0.26765597, 0.31903145],
       [0.10823065, 0.73824479, 0.66805892, 0.74723544, 0.542533  ,
        0.38350166, 0.59457898, 0.00622401, 0.09014365]])

In [45]:
l = np.identity(9)
l

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [46]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [54]:
import numpy as np
import pandas as pd

labels = ['a','s','h']
data = [20,22,25]
arr = np.array(data)
d = {'a':20,'s':22,'h':25}

print(labels)
print(data)
print(d)

['a', 's', 'h']
[20, 22, 25]
{'a': 20, 's': 22, 'h': 25}
